sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

lang: en-GB # Set the site language
title: Creative Prediction with Neural Networks
logo: "/assets/network_logo.svg" # Site logo, also used in jekyll-seo-tag
email: charlepm@ifi.uio.no
repo: "https://github.com/cpmpercussion/creative-prediction"

description: >- # this means to ignore newlines until "baseurl:"
  A course in ML/AI for creative expression
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://creativeprediction.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cpmpercussion
github_username:  cpmpercussion
# show_downloads: true
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

assets:
  sources:
    - assets/
    - assets/reveal.js/css/theme/source/ # required to pick up the ANU reveal.js theme file

markdown: kramdown
remote_theme: cpmpercussion/alembic
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
  
navigation_header:
- title: Home
  url: /
- title: NIME
  url: /nime/
- title: Tutorials
  url: /tutorials/
- title: Presentations
  url: /presentations/
- title: IMPS
  url: /imps/
- title: Setup
  url: /setup/

navigation_footer:
- title: Created by Charles Martin
  url: https://charlesmartin.com.au
- title: UiO EPEC Project
  url: https://www.hf.uio.no/ritmo/english/projects/all/epec/
- title: RTMO Centre for Interdisciplinary Studies in Rhythm Time and Motion
  url: https://www.hf.uio.no/ritmo/english/

exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

collections:
  presentations:
    output: true
  hack:
    output: true

